### ISSUE TITLE
What does the training data look like?

### ISSUE THREAD

**Issue by TechnikEmpire** [luke-lorenzini/Machine-Learning-Cpp#2]
I haven't done an in depth review of your code so forgive me if this is already answered. I'm wondering if you can include training and test data samples in the repo? All I see is two different formats of CSV (I think?) but no specifics

**Comment by luke-lorenzini** [comment]
I've included the IRIS data set I'm using for training. More changes and full write-up coming, just squashing the last few (until the next few) bugs.

Here's where the original data came from
https://archive.ics.uci.edu/ml/datasets/iris

It's a simple CSV file, the first 4 columns are input data, the last column is a number (0:2) representing the species. 

Line 64 in source.cpp, #if CLASS_DATA informs the program of where the data / labels are.

**Comment by TechnikEmpire** [comment]
Thank you.
